import type { Scene } from "../types";

export const act1: Scene[] = [
  {
    id: "s01",
    chapter: "الفصل الأول — المكالمة",
    title: "الشقة",
    time: "1:47 ص",
    place: "شقة دانيال فيل",
    bg: "apartment",
    mood: "rain",
    lines: [
      { who: "narrator", text: "شقة معتمة. المطر يضرب النافذة كأنه يحاول الدخول.", stage: true },
      {
        who: "narrator",
        text: "على الشاشة صورة حادث سيارة قديمة. إيلاياس فيل. خمس سنوات مضت.",
        stage: true,
      },
      { who: "daniel", text: "خمس سنوات… ولا سطر جديد." },
      { who: "narrator", text: "يغلق الملف. الهاتف يرن. رقم مجهول.", stage: true },
      { who: "unknown", text: "…" },
      { who: "narrator", text: "صمت. ثم نَفَس.", stage: true },
      { who: "unknown", text: "دانيال؟" },
      { who: "daniel", text: "من معي؟" },
      { who: "unknown", text: "لا تُشعل الأنوار." },
      { who: "daniel", text: "من أنتِ؟" },
      { who: "unknown", text: "أنت لا تتذكرني." },
      { who: "daniel", text: "عمّا تتحدثين؟" },
      { who: "unknown", text: "الغرفة ٣١٠." },
      { who: "daniel", text: "ما بها الغرفة ٣١٠؟" },
      { who: "unknown", text: "يعرفون أنك قادم." },
      { who: "narrator", text: "الخط يُقطع.", stage: true, shake: true },
      { who: "system", text: "فندق هالسيون\nتأكيد الحجز\nالضيف: دانيال فيل\nالغرفة: ٣١٠\nالوصول: الليلة" },
      { who: "daniel", text: "أنا لم أحجز شيئاً." },
    ],
    onEnter: { evidence: ["reservation"] },
    choicePrompt: "ماذا يفعل دانيال؟",
    choices: [
      {
        id: "ignore",
        text: "تجاهل الرسالة.",
        effect: { set: { ignoredCall: true }, trust: { claire: -5 } },
        goto: "s02",
      },
      {
        id: "hotel",
        text: "اتصل بالفندق.",
        effect: { set: { calledHotel: true }, trust: { victor: 5 } },
        goto: "s02",
      },
      {
        id: "police",
        text: "اتصل بالشرطة.",
        effect: { set: { calledPolice: true }, trust: { maya: 10, claire: -10 } },
        goto: "s02",
      },
      {
        id: "go",
        text: "اذهب إلى الفندق فوراً.",
        effect: { set: { wentImmediately: true }, trust: { claire: 10 } },
        goto: "s02",
      },
    ],
  },
  {
    id: "s02",
    chapter: "الفصل الأول — المكالمة",
    title: "الطريق",
    time: "2:04 ص",
    place: "شوارع المدينة",
    bg: "drive",
    mood: "rain",
    lines: [
      { who: "narrator", text: "مطر. أعمدة نور. راديو منخفض الصوت.", stage: true },
      {
        who: "system",
        text: "…وأعادت الشرطة فتح التحقيق في اختفاء عدد من السجلات المالية…",
      },
      { who: "narrator", text: "يُطفئ الراديو. الهاتف يهتز. صورة تصل.", stage: true },
      { who: "narrator", text: "الصورة هي دانيال. واقفاً أمام شقته. من الجهة المقابلة للشارع.", stage: true },
      { who: "system", text: "الطابع الزمني: 1:32 ص" },
      { who: "daniel", text: "قبل خمسة عشر دقيقة من المكالمة." },
      {
        who: "narrator",
        text: "ينظر في المرآة الخلفية. سيارة دفع رباعي سوداء. تختفي عند التقاطع التالي.",
        stage: true,
      },
    ],
    onEnter: { evidence: ["photo_apartment"] },
    next: "s03",
  },
  {
    id: "s03",
    chapter: "الفصل الأول — المكالمة",
    title: "هالسيون",
    time: "2:21 ص",
    place: "لوبي الفندق",
    bg: "lobby",
    mood: "cold",
    lines: [
      { who: "narrator", text: "لوبي ضخم. شبه فارغ. الرخام يلمع تحت ضوء بارد.", stage: true },
      { who: "narrator", text: "موظفة الاستقبال ترفع بصرها. تعرفه في اللحظة الأولى.", stage: true },
      { who: "receptionist", text: "سيد فيل." },
      { who: "daniel", text: "هل تقابلنا من قبل؟" },
      { who: "receptionist", text: "…لا." },
      { who: "narrator", text: "تعطيه بطاقة. ٣١٠.", stage: true },
      { who: "daniel", text: "من حجز الغرفة؟" },
      { who: "receptionist", text: "مكتوب أنك أنت من حجزها." },
      { who: "daniel", text: "لم أفعل." },
      { who: "receptionist", text: "ربما النظام…" },
      { who: "narrator", text: "قبل أن تُكمل، يظهر رجل خلف دانيال.", stage: true, shake: true },
      { who: "noah", text: "كل شيء بخير؟" },
      { who: "narrator", text: "نواه كين يبتسم.", stage: true },
      { who: "noah", text: "أهلاً بك في هالسيون." },
    ],
    inspectPrompt: "لاحظ ما حولك قبل أن تصعد.",
    minInspect: 1,
    inspect: [
      {
        id: "reception_screen",
        label: "شاشة الاستقبال",
        x: 34,
        y: 62,
        lines: [
          { who: "narrator", text: "سجل البطاقة يقول إن الغرفة ٣١٠ فُتحت الليلة. الساعة 12:58 ص.", stage: true },
          { who: "daniel", text: "قبل أن أستلم البطاقة بساعة ونصف." },
        ],
        effect: { evidence: ["keycard_log"], trust: { maya: 5 } },
      },
      {
        id: "lobby_camera",
        label: "كاميرا السقف",
        x: 72,
        y: 22,
        lines: [
          { who: "narrator", text: "الكاميرا تتبعه. ليست ثابتة على المدخل، بل عليه.", stage: true },
        ],
        effect: { secrets: ["hotel_is_facility"] },
      },
      {
        id: "noah_hands",
        label: "يدا نواه",
        x: 58,
        y: 55,
        lines: [
          { who: "narrator", text: "وشم عسكري قديم تحت الكم. وسلسلة مفاتيح ثقيلة على حزامه.", stage: true },
          { who: "daniel", text: "حرس فندق لا يحمل هذا العدد من المفاتيح." },
        ],
        effect: { trust: { noah: 5 } },
      },
    ],
    next: "s04",
  },
  {
    id: "s04",
    chapter: "الفصل الأول — المكالمة",
    title: "المصعد",
    time: "2:26 ص",
    place: "مصعد الفندق",
    bg: "hallway",
    mood: "cold",
    lines: [
      { who: "narrator", text: "الأبواب تُغلق. نواه يدخل خلفه. صمت.", stage: true },
      { who: "narrator", text: "نواه يضغط الرقم ٣. دانيال لم يضغط شيئاً.", stage: true },
      { who: "noah", text: "لم تتغير كثيراً." },
      { who: "daniel", text: "هل أعرفك؟" },
      { who: "noah", text: "ليس شخصياً." },
    ],
    choicePrompt: "ماذا يقول دانيال؟",
    choices: [
      {
        id: "press",
        text: "«إذاً كيف تعرفني؟»",
        effect: { trust: { noah: -10 } },
        goto: "s04b",
      },
      {
        id: "silent",
        text: "لا شيء. راقبه فقط.",
        effect: { trust: { noah: 10 } },
        goto: "s04b",
      },
      {
        id: "lie",
        text: "«أنا هنا للعمل. لا شيء أكثر.»",
        effect: { trust: { noah: 5 }, secrets: [] },
        goto: "s04b",
      },
    ],
  },
  {
    id: "s04b",
    chapter: "الفصل الأول — المكالمة",
    title: "الطابق الثالث",
    time: "2:28 ص",
    place: "ممر الطابق الثالث",
    bg: "hallway",
    mood: "cold",
    lines: [
      { who: "narrator", text: "المصعد يتوقف. الطابق الثالث. نواه يخرج.", stage: true },
      { who: "noah", text: "لا تسهر كثيراً." },
      { who: "narrator", text: "الأبواب تُغلق.", stage: true },
    ],
    next: "s05",
  },
  {
    id: "s05",
    chapter: "الفصل الأول — المكالمة",
    title: "الغرفة ٣١٠",
    time: "2:34 ص",
    place: "الغرفة ٣١٠",
    bg: "room310",
    mood: "dark",
    lines: [
      { who: "narrator", text: "يفتح الباب. عتمة. يُشعل الضوء.", stage: true },
      { who: "narrator", text: "سرير. مكتب. حمّام. نافذة. كل شيء طبيعي.", stage: true },
      { who: "narrator", text: "ثم يلاحظ شيئاً. لطخة حمراء تحت السرير.", stage: true, shake: true },
      { who: "daniel", text: "دماء." },
      { who: "narrator", text: "يسحب هاتفاً محمولاً مكسوراً. شاشة القفل تقول:", stage: true },
      { who: "system", text: "كلير ميرسر" },
      { who: "daniel", text: "أنا حققت في موتها قبل ثمانية أشهر." },
      { who: "narrator", text: "الهاتف يهتز. إشعار واحد.", stage: true },
      { who: "system", text: "فيديو — 00:47" },
      { who: "claire", text: "دانيال، إذا كنت تشاهد هذا… لا تثق بالشرطة." },
      { who: "narrator", text: "ينتهي الفيديو.", stage: true },
    ],
    onEnter: { evidence: ["blood_stain", "claire_phone", "claire_video"] },
    next: "s06",
  },
];
