import type { Scene } from "../types";

export const act2: Scene[] = [
  {
    id: "s06",
    chapter: "الفصل الثاني — الغرفة",
    title: "الكاميرا المخفية",
    time: "2:48 ص",
    place: "الغرفة ٣١٠",
    bg: "room310",
    mood: "dark",
    lines: [
      { who: "daniel", text: "شخص ما أراد أن أكون هنا. إذاً شخص ما يشاهد." },
      { who: "narrator", text: "يبدأ بتفتيش الغرفة، قطعة قطعة.", stage: true },
    ],
    inspectPrompt: "افحص الغرفة. لا شيء يقول لك ما هو المهم.",
    minInspect: 3,
    inspect: [
      {
        id: "smoke_detector",
        label: "كاشف الدخان",
        x: 50,
        y: 12,
        lines: [
          { who: "narrator", text: "يفكّ الغطاء. عدسة بحجم رأس دبوس. ضوء أحمر صغير. ما زالت تعمل.", stage: true },
          { who: "narrator", text: "ينظر مباشرة في العدسة. الضوء الأحمر يُطفأ.", stage: true, shake: true },
          { who: "daniel", text: "أنت هناك." },
        ],
        effect: {
          evidence: ["hidden_camera"],
          secrets: ["hotel_is_facility"],
          set: { foundHiddenCamera: true },
        },
      },
      {
        id: "bathroom_mirror",
        label: "مرآة الحمّام",
        x: 82,
        y: 44,
        lines: [
          { who: "narrator", text: "المرآة تتحرك قليلاً. خلفها خدوش على الجبس.", stage: true },
          { who: "system", text: "٣ ١ ٠ ب" },
          { who: "daniel", text: "٣١٠… ب؟" },
        ],
        effect: { evidence: ["mirror_scratch"], secrets: ["room310b"] },
      },
      {
        id: "air_vent",
        label: "فتحة التهوية",
        x: 15,
        y: 30,
        lines: [
          { who: "narrator", text: "ورقة مطوية، مبلّلة من الأسفل. خط امرأة مستعجل.", stage: true },
          { who: "system", text: "«إن قرأتَ هذا فأنا لم أستطع الانتظار. القبو. خلف النبيذ.»" },
        ],
        effect: { evidence: ["vent_note"], trust: { claire: 10 } },
      },
      {
        id: "tv",
        label: "التلفاز",
        x: 66,
        y: 52,
        lines: [
          { who: "narrator", text: "القائمة تعرض اسم ضيف مختلف: إ. فيل. غرفة ٣١٠.", stage: true },
          { who: "daniel", text: "…إيلاياس." },
        ],
        effect: { secrets: ["elias_alive"], trust: { claire: 5 } },
      },
      {
        id: "bed_frame",
        label: "إطار السرير",
        x: 38,
        y: 72,
        lines: [
          { who: "narrator", text: "خدش عميق في الخشب، وشعرة واحدة داكنة عالقة فيه.", stage: true },
          { who: "daniel", text: "شخص ما قاوَم هنا." },
        ],
      },
      {
        id: "window",
        label: "النافذة",
        x: 90,
        y: 26,
        lines: [
          { who: "narrator", text: "أسفل الفندق مباشرة: سيارة دفع رباعي سوداء. متوقفة. المحرك يعمل.", stage: true },
        ],
        effect: { trust: { noah: -5 } },
      },
      {
        id: "desk",
        label: "المكتب",
        x: 24,
        y: 56,
        lines: [
          { who: "narrator", text: "دفتر ملاحظات الفندق. الصفحة الأولى مقتلعة. آثار الضغط باقية.", stage: true },
          { who: "system", text: "«لا تعطِ الأدلة لأحد قبل أن تعرف من قتل إيلاياس.»" },
        ],
        effect: { secrets: ["memory_wiped"] },
      },
    ],
    next: "s07",
  },
  {
    id: "s07",
    chapter: "الفصل الثاني — الغرفة",
    title: "الاختيار الأول",
    time: "3:02 ص",
    place: "الغرفة ٣١٠",
    bg: "room310",
    mood: "dark",
    lines: [
      { who: "narrator", text: "الهاتف المكسور يهتز مرة أخرى. رسالة واحدة.", stage: true },
      { who: "unknown", text: "كان عليك أن تبقى في بيتك." },
    ],
    choicePrompt: "بماذا يجيب؟",
    choices: [
      {
        id: "who",
        text: "«من أنت؟»",
        effect: { set: { answeredSender: "who" }, trust: { claire: -5 } },
        goto: "s08",
      },
      {
        id: "claire",
        text: "«أعرف ما حدث لكلير.»",
        effect: { set: { answeredSender: "claire" }, trust: { claire: 15, victor: -10 } },
        goto: "s08",
      },
      {
        id: "come",
        text: "«تعال وجدني.»",
        effect: { set: { answeredSender: "come" }, trust: { noah: 10, victor: -5 } },
        goto: "s08",
      },
      {
        id: "none",
        text: "لا ترد. اترك الهاتف على المكتب.",
        effect: { set: { answeredSender: "none" }, trust: { victor: 5 } },
        goto: "s08",
      },
    ],
  },
  {
    id: "s08",
    chapter: "الفصل الثاني — الغرفة",
    title: "انقطاع الكهرباء",
    time: "3:11 ص",
    place: "ممر الطابق الثالث",
    bg: "hallway_red",
    mood: "red",
    lines: [
      { who: "narrator", text: "ظلام كامل.", stage: true, shake: true },
      { who: "narrator", text: "أنوار الطوارئ تشتعل. الفندق كله يصبح أحمر.", stage: true },
      { who: "narrator", text: "خطوات خارج الغرفة ٣١٠. يفتح الباب. لا أحد.", stage: true },
      { who: "narrator", text: "في نهاية الممر: امرأة.", stage: true, shake: true },
      { who: "daniel", text: "…كلير." },
      { who: "narrator", text: "تنظر إليه. ثم تجري.", stage: true },
    ],
    onEnter: { evidence: ["hallway_sighting"], secrets: ["claire_alive"], set: { sawClaireInHallway: true } },
    choicePrompt: "الممر أحمر والخطوات تبتعد.",
    choices: [
      { id: "chase", text: "اتبعها.", effect: { trust: { claire: 15 } }, goto: "s09" },
      {
        id: "stay",
        text: "ابقَ. صوّر الممر بهاتفك.",
        effect: { trust: { claire: -10, maya: 10 } },
        goto: "s09",
      },
    ],
  },
  {
    id: "s09",
    chapter: "الفصل الثاني — الغرفة",
    title: "المطاردة",
    time: "3:15 ص",
    place: "ممرات الخدمة",
    bg: "hallway_red",
    mood: "red",
    lines: [
      { who: "narrator", text: "تختفي عند الزاوية. يصل إلى باب خدمة مقفل.", stage: true },
      { who: "narrator", text: "يد تقبض على كتفه من الخلف.", stage: true, shake: true },
      { who: "noah", text: "ماذا تفعل هنا؟" },
      { who: "daniel", text: "رأيتها." },
      { who: "noah", text: "رأيت من؟" },
      { who: "daniel", text: "كلير." },
      { who: "narrator", text: "ملامح نواه تتغير. لثانية واحدة فقط. ثم تعود.", stage: true },
    ],
    choicePrompt: "نواه يقف بينك وبين الباب.",
    choices: [
      {
        id: "steal_key",
        text: "اشغله بالكلام… وخذ المفتاح من حزامه.",
        hint: "خطر",
        effect: { set: { stoleNoahKey: true }, trust: { noah: -20 } },
        goto: "s10",
      },
      {
        id: "demand",
        text: "«أرني غرفة المراقبة. الآن.»",
        effect: { trust: { noah: 10 }, set: { enteredSecurityRoom: true } },
        goto: "s10",
      },
      {
        id: "retreat",
        text: "تراجَع. اعتذر. راقبه من بعيد.",
        effect: { trust: { noah: 5, claire: -5 } },
        goto: "s11",
      },
    ],
  },
  {
    id: "s10",
    chapter: "الفصل الثاني — الغرفة",
    title: "غرفة المراقبة",
    time: "3:31 ص",
    place: "غرفة المراقبة",
    bg: "security",
    mood: "cold",
    lines: [
      { who: "narrator", text: "عشرات الشاشات. كل ممر. كل مصعد. كل غرفة.", stage: true },
      { who: "narrator", text: "إلا واحدة.", stage: true },
      { who: "daniel", text: "الغرفة ٣١٠ ليس لها تغذية." },
      { who: "narrator", text: "لكن هناك أرشيف. يبحث عن اسم.", stage: true },
    ],
    onEnter: { evidence: ["no_camera_310"], set: { enteredSecurityRoom: true } },
    inspectPrompt: "الأرشيف مفتوح. لديك دقائق قبل أن يعود التيار.",
    minInspect: 1,
    inspect: [
      {
        id: "archive_claire",
        label: "أرشيف: كلير ميرسر",
        x: 30,
        y: 40,
        lines: [
          { who: "narrator", text: "قبل ثمانية أشهر. كلير تدخل الغرفة ٣١٠.", stage: true },
          { who: "narrator", text: "لا تظهر خارجة منها أبداً.", stage: true },
          { who: "narrator", text: "يُرجع الشريط. 3:04 ص — شخص يدخل بعدها.", stage: true, shake: true },
          { who: "narrator", text: "زي صيانة. الوجه مخفي. يعرف مكان الكاميرا ويتجنبها.", stage: true },
        ],
        effect: {
          evidence: ["archive_footage", "maintenance_uniform"],
          set: { sawArchiveFootage: true },
        },
      },
      {
        id: "archive_daniel",
        label: "أرشيف: دانيال فيل",
        x: 62,
        y: 36,
        lines: [
          { who: "narrator", text: "المجلد موجود. لكنه ضخم. سنوات، لا ليال.", stage: true },
          { who: "daniel", text: "أنا لم أزر هذا الفندق في حياتي." },
        ],
        effect: { secrets: ["memory_wiped"] },
      },
      {
        id: "archive_orpheus_hint",
        label: "مجلد بلا اسم",
        x: 48,
        y: 68,
        lines: [
          { who: "narrator", text: "مجلد واحد بلا عنوان، محمي بكلمة مرور. الوصف حرفان: «أ.ر»", stage: true },
        ],
        effect: { secrets: ["orpheus"] },
      },
    ],
    next: "s11",
  },
  {
    id: "s11",
    chapter: "الفصل الثاني — الغرفة",
    title: "مايا",
    time: "4:02 ص",
    place: "لوبي الفندق",
    bg: "lobby",
    mood: "cold",
    lines: [
      { who: "narrator", text: "يتصل سراً بالمحققة مايا ريد. تصل بعد نصف ساعة.", stage: true },
      { who: "maya", text: "قلتَ إن كلير اتصلت بك." },
      { who: "daniel", text: "اتصلت." },
      { who: "maya", text: "كلير ميتة." },
      { who: "narrator", text: "يُخرج الهاتف المكسور. تتعرف عليه فوراً. ملامحها تتغير.", stage: true },
      { who: "maya", text: "من أين أخذت هذا؟" },
      { who: "daniel", text: "الغرفة ٣١٠." },
      { who: "maya", text: "هذا مستحيل." },
      { who: "daniel", text: "لماذا؟" },
      { who: "narrator", text: "لا تجيب.", stage: true },
    ],
    choicePrompt: "ستسألك مايا عمّا رأيته في الممر.",
    choices: [
      {
        id: "truth",
        text: "قل الحقيقة: «رأيتها. حيّة.»",
        effect: { trust: { maya: 20, claire: -5 }, set: { liedToMaya: false } },
        goto: "s12",
      },
      {
        id: "lie",
        text: "اكذب: «لم أرَ أحداً. وجدت الهاتف فقط.»",
        hint: "ستتذكر مايا هذه الليلة",
        effect: { trust: { maya: 5, claire: 10 }, set: { liedToMaya: true } },
        goto: "s12",
      },
      {
        id: "half",
        text: "نصف حقيقة: «رأيت امرأة. لا أعرف من.»",
        effect: { trust: { maya: 10 } },
        goto: "s12",
      },
    ],
  },
];
