import type { Scene } from "../types";

export const act3: Scene[] = [
  {
    id: "s12",
    chapter: "الفصل الثالث — المرأة التي ماتت",
    title: "ملف التشريح",
    time: "4:24 ص",
    place: "مطعم الفندق المغلق",
    bg: "lobby",
    mood: "cold",
    lines: [
      { who: "narrator", text: "مايا تفتح حاسوبها على طاولة مطعم مغلق. ملف كلير.", stage: true },
      { who: "maya", text: "رسمياً: توفيت في منزلها." },
      { who: "narrator", text: "لكن في التقرير سطر غريب.", stage: true },
      { who: "maya", text: "مهدئات في الدم. بجرعة تُفقد الوعي، لا تقتل." },
      { who: "daniel", text: "ألم تقرئي هذا وقتها؟" },
      { who: "maya", text: "التقرير الذي وصلني لم يكن فيه هذا السطر." },
      { who: "narrator", text: "تضع يدها على فمها. ليست مفاجأة. إنها بداية غضب.", stage: true },
      { who: "maya", text: "شخص ما عدّل تقرير تشريح في قضية أنا مسؤولة عنها." },
    ],
    onEnter: { evidence: ["autopsy_report", "sedatives"], trust: { maya: 10 } },
    next: "s13",
  },
  {
    id: "s13",
    chapter: "الفصل الثالث — المرأة التي ماتت",
    title: "القبو",
    time: "4:51 ص",
    place: "قبو الفندق",
    bg: "basement",
    mood: "dark",
    lines: [
      { who: "narrator", text: "مخزن قديم. رطوبة. باب معدني مقفل.", stage: true },
      { who: "narrator", text: "مايا تفتحه بطريقة لا يسألها دانيال عنها.", stage: true },
      { who: "narrator", text: "مئات الصناديق. سجلات ضيوف. أشرطة. مستندات مالية.", stage: true },
    ],
    inspectPrompt: "الصناديق كثيرة والوقت قليل.",
    minInspect: 2,
    inspect: [
      {
        id: "orpheus",
        label: "مجلد: مشروع أورفيوس",
        x: 40,
        y: 50,
        lines: [
          { who: "narrator", text: "داخل المجلد صورة واحدة.", stage: true },
          { who: "narrator", text: "كلير. إيلاياس. نواه. فيكتور.", stage: true },
          { who: "narrator", text: "ودانيال.", stage: true, shake: true },
          { who: "system", text: "الطابع الزمني: قبل خمس سنوات" },
          { who: "daniel", text: "أنا لم أرَ هذه الصورة في حياتي." },
        ],
        effect: {
          evidence: ["orpheus_folder", "group_photo"],
          secrets: ["orpheus", "memory_wiped"],
          set: { discoveredOrpheus: true },
        },
      },
      {
        id: "guest_files",
        label: "سجلات الضيوف",
        x: 68,
        y: 58,
        lines: [
          { who: "narrator", text: "أسماء لا ينبغي أن تكون في فندق: قضاة، نواب، ضابط شرطة اثنان.", stage: true },
          { who: "narrator", text: "بجوار كل اسم رقم غرفة. أكثرها: ٣١٠.", stage: true },
        ],
        effect: { secrets: ["hotel_is_facility"], trust: { maya: 5 } },
      },
      {
        id: "financials",
        label: "مستندات مالية",
        x: 22,
        y: 66,
        lines: [
          { who: "narrator", text: "مدفوعات شهرية من شركة أمن خاصة. نفس الشركة التي حقق فيها دانيال قبل خمس سنوات.", stage: true },
          { who: "daniel", text: "التحقيق الذي اختفى." },
        ],
        effect: { secrets: ["circle"] },
      },
    ],
    next: "s14",
  },
  {
    id: "s14",
    chapter: "الفصل الثالث — المرأة التي ماتت",
    title: "الذكرى",
    time: "قبل خمس سنوات",
    place: "استرجاع",
    bg: "apartment",
    mood: "warm",
    lines: [
      { who: "narrator", text: "ضوء نهار باهت. صوت المسجّل يدور.", stage: true },
      { who: "elias", text: "إذا حدث لي شيء… لا تصدّق قصة الحادث." },
      { who: "daniel", text: "ماذا وجدت؟" },
      { who: "elias", text: "غرفة." },
      { who: "daniel", text: "أي غرفة؟" },
      { who: "elias", text: "٣١٠." },
      { who: "narrator", text: "ينتهي الاسترجاع.", stage: true, shake: true },
      { who: "daniel", text: "أخي كان يعرف عن هذه الغرفة." },
    ],
    onEnter: { secrets: ["elias_alive"] },
    next: "s15",
  },
  {
    id: "s15",
    chapter: "الفصل الثالث — المرأة التي ماتت",
    title: "فيكتور هيل",
    time: "5:10 ص",
    place: "قبو الفندق",
    bg: "basement",
    mood: "dark",
    lines: [
      { who: "narrator", text: "الضوء يشتعل خلفهما. فيكتور هيل. هادئ. أنيق. غير مستعجل.", stage: true },
      { who: "victor", text: "محققة ريد." },
      { who: "narrator", text: "يد مايا تتحرك نحو سلاحها.", stage: true },
      { who: "victor", text: "لو أردت أحدكما ميتاً، لما كنتما واقفين هنا." },
      { who: "daniel", text: "ما هو مشروع أورفيوس؟" },
      { who: "victor", text: "شيء ما كان يجب أن يجده أخوك." },
      { who: "daniel", text: "أنت قتلته." },
      { who: "victor", text: "لا." },
      { who: "narrator", text: "صمت طويل.", stage: true },
      { who: "victor", text: "أنا حاولت أن أنقذه." },
    ],
    choicePrompt: "فيكتور يقف أمامك بلا سلاح.",
    choices: [
      {
        id: "believe",
        text: "«إذاً أخبرني كيف.»",
        effect: { trust: { victor: 20 } },
        goto: "s16",
      },
      {
        id: "accuse",
        text: "«أنت تكذب كما يكذب الجميع هنا.»",
        effect: { trust: { victor: -15, maya: 5 } },
        goto: "s16",
      },
      {
        id: "silence",
        text: "لا تقل شيئاً. دوّن وجهه في ذاكرتك.",
        effect: { trust: { victor: 5 } },
        goto: "s16",
      },
    ],
  },
  {
    id: "s16",
    chapter: "الفصل الثالث — المرأة التي ماتت",
    title: "التسجيل",
    time: "5:26 ص",
    place: "قبو الفندق",
    bg: "basement",
    mood: "dark",
    lines: [
      { who: "narrator", text: "فيكتور يخرج. دانيال يجد مسجّلاً صوتياً قديماً بين الصناديق.", stage: true },
      { who: "elias", text: "دانيال. إذا وجدت هذا، فأنا آسف." },
      { who: "elias", text: "هناك أناس يدفعون للفندق مقابل مراقبة الضيوف." },
      { who: "elias", text: "سياسيون. رجال أعمال. ضباط شرطة." },
      { who: "narrator", text: "صمت على الشريط.", stage: true },
      { who: "elias", text: "هم لا يصوّرون الناس من أجل المال." },
      { who: "elias", text: "يصوّرونهم لأن كل إنسان لديه ما يخفيه." },
      { who: "narrator", text: "ثم:", stage: true },
      { who: "elias", text: "كلير وجدت الأرشيف." },
      { who: "narrator", text: "ينتهي التسجيل.", stage: true },
    ],
    onEnter: {
      evidence: ["elias_recorder"],
      secrets: ["hotel_is_facility", "orpheus"],
      set: { foundEliasRecorder: true },
    },
    next: "s17",
  },
];
