import type { Scene } from "../types";

export const act4: Scene[] = [
  {
    id: "s17",
    chapter: "الفصل الرابع — الأرشيف",
    title: "المصعد السري",
    time: "5:44 ص",
    place: "مخزن النبيذ",
    bg: "basement",
    mood: "dark",
    lines: [
      { who: "narrator", text: "خلف رفوف النبيذ جدار متحرك. وخلفه باب مصعد بلا أرقام.", stage: true },
      { who: "narrator", text: "فتحة مفتاح واحدة. لا لوحة أزرار.", stage: true },
      { who: "maya", text: "هذا ليس في أي مخطط للمبنى." },
    ],
    choicePrompt: "المصعد يحتاج مفتاحاً. لديك ثلاث طرق.",
    choices: [
      {
        id: "noah_key",
        text: "استخدم مفتاح نواه الذي سرقته.",
        requires: (s) => s.flags.stoleNoahKey,
        effect: { trust: { noah: -10 } },
        goto: "s18",
      },
      {
        id: "victor_key",
        text: "اطلب المفتاح من فيكتور.",
        requires: (s) => s.trust.victor >= 15,
        effect: { set: { victorGaveKey: true }, trust: { victor: 10 } },
        goto: "s18",
      },
      {
        id: "claire_key",
        text: "ابحث عن مفتاح كلير حيث قالت لك الورقة.",
        requires: (s) => s.evidence.includes("vent_note") || s.trust.claire >= 30,
        effect: { set: { foundClaireKey: true }, trust: { claire: 15 } },
        goto: "s18",
      },
      {
        id: "force",
        text: "اكسر اللوحة. سيعرفون أنك هنا.",
        effect: { trust: { noah: -15, victor: -15 } },
        goto: "s18",
      },
    ],
  },
  {
    id: "s18",
    chapter: "الفصل الرابع — الأرشيف",
    title: "تحت الأرض",
    time: "5:58 ص",
    place: "الأرشيف السفلي",
    bg: "archive",
    mood: "cold",
    lines: [
      { who: "narrator", text: "المصعد ينزل. ببطء شديد. لا إشارة. لا إنترنت. لا كاميرات.", stage: true },
      { who: "narrator", text: "الأبواب تُفتح.", stage: true, shake: true },
      { who: "narrator", text: "قاعة ضخمة. صفوف من الأقراص الصلبة. خوادم. صور. تسجيلات. مستندات.", stage: true },
      { who: "daniel", text: "هذا لم يكن فندقاً قط." },
      { who: "maya", text: "هذه منشأة." },
    ],
    onEnter: {
      evidence: ["server_index"],
      secrets: ["hotel_is_facility"],
      set: { discoveredArchive: true },
    },
    next: "s19",
  },
  {
    id: "s19",
    chapter: "الفصل الرابع — الأرشيف",
    title: "ملف دانيال",
    time: "6:07 ص",
    place: "الأرشيف السفلي",
    bg: "archive",
    mood: "cold",
    lines: [{ who: "narrator", text: "طرفية واحدة. حقل بحث واحد. يكتب اسمه.", stage: true }],
    inspectPrompt: "ابحث في الأرشيف.",
    minInspect: 2,
    inspect: [
      {
        id: "file_daniel",
        label: "دانيال فيل",
        x: 34,
        y: 44,
        lines: [
          { who: "system", text: "دانيال فيل\nالعمر عند الفتح: ٢٦\nالمهنة: صحافي\nالحالة: مُراقَب" },
          { who: "narrator", text: "تسجيلات من شقته. مكالماته. تحقيقاته. أحاديثه مع إيلاياس.", stage: true },
          { who: "daniel", text: "خمس سنوات… وأنا أعتقد أنني أُحقق." },
        ],
        effect: { evidence: ["daniel_file"], secrets: ["memory_wiped"] },
      },
      {
        id: "file_elias",
        label: "إيلاياس فيل",
        x: 62,
        y: 40,
        lines: [
          { who: "system", text: "إيلاياس فيل\nالحالة: مُنتهى" },
          { who: "narrator", text: "دانيال يتجمّد. الكلمة ليست «متوفى». الكلمة إجراء.", stage: true, shake: true },
        ],
        effect: { evidence: ["elias_file"], secrets: ["circle"] },
      },
      {
        id: "file_sites",
        label: "خريطة المواقع",
        x: 48,
        y: 70,
        lines: [
          { who: "narrator", text: "سبعة عشر دبوساً على الخريطة. هالسيون واحد منها فقط.", stage: true },
        ],
        effect: { secrets: ["seventeen_sites", "circle"], set: { discoveredCircle: true } },
      },
      {
        id: "file_victor",
        label: "فيكتور هيل",
        x: 20,
        y: 60,
        lines: [
          { who: "system", text: "فيكتور هيل\nالحالة: مُشغّل موقع — الرتبة ٤" },
          { who: "daniel", text: "الرتبة أربعة. إذاً هناك ثلاث فوقه." },
        ],
        effect: { secrets: ["victor_is_employee", "circle"] },
      },
    ],
    next: "s20",
  },
  {
    id: "s20",
    chapter: "الفصل الرابع — الأرشيف",
    title: "الثماني عشرة دقيقة",
    time: "6:22 ص",
    place: "الأرشيف السفلي",
    bg: "archive",
    mood: "cold",
    lines: [
      { who: "narrator", text: "مايا تجد التقرير الأصلي للحادث. النسخة التي لم تصل لأحد.", stage: true },
      { who: "maya", text: "إيلاياس لم يمت على الفور." },
      { who: "maya", text: "السيارة انقلبت. وبقي حياً ثماني عشرة دقيقة." },
      { who: "narrator", text: "خلال تلك الدقائق وصلت سيارة. دفع رباعي سوداء.", stage: true },
      { who: "maya", text: "شخص أخرج إيلاياس من السيارة." },
      { who: "daniel", text: "التقرير الرسمي يقول: لا شهود." },
      { who: "narrator", text: "الأرشيف يقول غير ذلك. الأرشيف فيه اسم.", stage: true, shake: true },
      { who: "system", text: "نواه كين — حاضر في الموقع" },
    ],
    onEnter: {
      evidence: ["police_report", "eighteen_minutes"],
      secrets: ["noah_at_crash"],
    },
    next: "s21",
  },
  {
    id: "s21",
    chapter: "الفصل الرابع — الأرشيف",
    title: "اعتراف نواه",
    time: "6:35 ص",
    place: "الأرشيف السفلي",
    bg: "archive",
    mood: "red",
    lines: [
      { who: "narrator", text: "نواه يظهر بين الرفوف. سلاحه مرفوع نحو دانيال.", stage: true, shake: true },
      { who: "narrator", text: "مايا ترفع سلاحها نحو نواه.", stage: true },
      { who: "noah", text: "أنا لم أقتل إيلاياس." },
      { who: "daniel", text: "فمن قتله؟" },
      { who: "noah", text: "أخوك كان يعرف أكثر مما ينبغي." },
      { who: "daniel", text: "كنت هناك." },
      { who: "noah", text: "نعم." },
      { who: "daniel", text: "لماذا؟" },
      { who: "noah", text: "لأنني أُمرت بأن أتأكد أنه لن يصل إلى المستشفى." },
      { who: "narrator", text: "يداه ترتجفان. لأول مرة الليلة.", stage: true },
    ],
    onEnter: { set: { noahConfessed: true } },
    choicePrompt: "سلاح مرفوع، واعتراف في الهواء.",
    choices: [
      {
        id: "forgive",
        text: "«من أمرك؟ أخبرني وسأخرجك من هنا.»",
        effect: { trust: { noah: 25 } },
        goto: "s22",
      },
      {
        id: "rage",
        text: "«أنت تركته يموت ببطء.»",
        effect: { trust: { noah: -25, claire: 5 } },
        goto: "s22",
      },
      {
        id: "maya_take",
        text: "«مايا. اعتقليه. سنجعله يشهد.»",
        effect: { trust: { maya: 20, noah: -10 } },
        goto: "s22",
      },
    ],
  },
];
