import type { Scene } from "../types";

export const act5: Scene[] = [
  {
    id: "s22",
    chapter: "الفصل الخامس — كلير",
    title: "الكاميرا الحيّة",
    time: "6:49 ص",
    place: "الأرشيف السفلي",
    bg: "archive",
    mood: "cold",
    lines: [
      { who: "narrator", text: "شاشة في نهاية الصف تشتعل وحدها.", stage: true, shake: true },
      { who: "narrator", text: "كلير. مباشرة. ليست تسجيلاً.", stage: true },
      { who: "daniel", text: "كلير؟" },
      { who: "claire", text: "وجدته." },
      { who: "daniel", text: "أنتِ حيّة." },
      { who: "claire", text: "حتى الآن." },
      { who: "claire", text: "زيّفت موتي بعد أن وجدت أورفيوس. هربت. وهم يطاردونني منذ ثمانية أشهر." },
      { who: "claire", text: "أحضرتُك لأنني أحتاج شخصاً يستطيع أن يفضح كل شيء." },
      { who: "claire", text: "لكنني لم أتوقع أن تصل بهذه السرعة." },
      { who: "daniel", text: "لماذا الغرفة ٣١٠؟" },
      { who: "claire", text: "لأنها المكان الوحيد الذي لا يستطيعون تصويره." },
    ],
    onEnter: { secrets: ["claire_alive"], evidence: [] },
    next: "s23",
  },
  {
    id: "s23",
    chapter: "الفصل الخامس — كلير",
    title: "الخيانة",
    time: "7:02 ص",
    place: "الأرشيف السفلي",
    bg: "archive",
    mood: "red",
    lines: [
      { who: "claire", text: "دمّر الأرشيف. كله. الآن." },
      { who: "maya", text: "لا. هذا دليل. بدونه لا يُحاسَب أحد." },
      { who: "noah", text: "اخرجوا جميعاً. لديكم أربع دقائق قبل أن يُغلق المبنى.", requires: (s) => s.alive.noah },
      { who: "victor", text: "الأرشيف يُحمى. هذا كل ما أستطيع تقديمه لكم." },
      { who: "narrator", text: "أربعة أصوات. وحقيقة واحدة.", stage: true },
    ],
    choicePrompt: "بمن تثق؟",
    choices: [
      {
        id: "claire",
        text: "كلير.",
        effect: { set: { trustedAt23: "claire" }, trust: { claire: 25, maya: -10 } },
        goto: "s23a",
      },
      {
        id: "maya",
        text: "مايا.",
        effect: { set: { trustedAt23: "maya" }, trust: { maya: 25, claire: -10 } },
        goto: "s23b",
      },
      {
        id: "noah",
        text: "نواه.",
        requires: (s) => s.alive.noah,
        effect: { set: { trustedAt23: "noah" }, trust: { noah: 25 } },
        goto: "s23c",
      },
      {
        id: "victor",
        text: "فيكتور.",
        effect: { set: { trustedAt23: "victor" }, trust: { victor: 25, claire: -15 } },
        goto: "s23d",
      },
    ],
  },
  {
    id: "s23a",
    chapter: "الفصل الخامس — كلير",
    title: "المسار: كلير",
    place: "الخادم المركزي",
    bg: "archive",
    mood: "cold",
    lines: [
      { who: "narrator", text: "دانيال يساعد كلير في الوصول إلى الخادم المركزي.", stage: true },
      { who: "claire", text: "أورفيوس ليس هذا الفندق فقط." },
      { who: "narrator", text: "الخريطة تفتح. سبعة عشر موقعاً آخر. هالسيون رقم أحد عشر.", stage: true },
      { who: "daniel", text: "هذه ليست جريمة. هذه دولة صغيرة." },
    ],
    onEnter: { secrets: ["seventeen_sites", "circle"], set: { discoveredCircle: true } },
    next: "s24",
  },
  {
    id: "s23b",
    chapter: "الفصل الخامس — كلير",
    title: "المسار: مايا",
    place: "الأرشيف السفلي",
    bg: "archive",
    mood: "cold",
    lines: [
      { who: "narrator", text: "مايا تنسخ كل شيء على قرصين. تتصل بمحققين فيدراليين.", stage: true },
      { who: "narrator", text: "المكالمة تُقطع في منتصفها. ليس انقطاع شبكة. اعتراض.", stage: true, shake: true },
      { who: "narrator", text: "خارج الفندق: سيارات شرطة. كثيرة.", stage: true },
      { who: "maya", text: "…هؤلاء ليسوا هنا لمساعدتنا." },
    ],
    onEnter: { secrets: ["circle"], set: { discoveredCircle: true }, trust: { maya: 10 } },
    next: "s24",
  },
  {
    id: "s23c",
    chapter: "الفصل الخامس — كلير",
    title: "المسار: نواه",
    place: "ممر الخدمة",
    bg: "security",
    mood: "red",
    lines: [
      { who: "noah", text: "فيكتور ليس العقل المدبر. فيكتور موظف." },
      { who: "daniel", text: "فمن؟" },
      { who: "noah", text: "المنظمة تُسمّى الدائرة." },
      { who: "noah", text: "أنا أحاول الخروج منها منذ أربع سنوات. لا أحد يخرج." },
      { who: "daniel", text: "لماذا تخبرني الآن؟" },
      { who: "noah", text: "لأنك الوحيد الذي لديه سبب لا يُشترى." },
    ],
    onEnter: {
      secrets: ["circle", "victor_is_employee"],
      set: { discoveredCircle: true },
      trust: { noah: 10 },
    },
    next: "s24",
  },
  {
    id: "s23d",
    chapter: "الفصل الخامس — كلير",
    title: "المسار: فيكتور",
    place: "مكتب المدير",
    bg: "security",
    mood: "warm",
    lines: [
      { who: "victor", text: "اعرض عليك شيئاً واحداً. انسَ الليلة." },
      { who: "daniel", text: "وكلير؟" },
      { who: "victor", text: "تختفي." },
      { who: "daniel", text: "مرة أخرى؟" },
      { who: "victor", text: "نهائياً." },
      { who: "narrator", text: "يضع مفتاحاً على الطاولة. ثم ظرفاً.", stage: true },
    ],
    choicePrompt: "الظرف مفتوح على الطاولة.",
    choices: [
      {
        id: "refuse",
        text: "«لا.»",
        effect: { trust: { victor: -10 }, set: { refusedEveryDeal: true } },
        goto: "s24",
      },
      {
        id: "consider",
        text: "خُذ الظرف. لا تفتحه.",
        effect: { trust: { victor: 15 }, set: { refusedEveryDeal: false } },
        goto: "s24",
      },
    ],
  },
];
