import type { Scene } from "../types";

export const act6: Scene[] = [
  {
    id: "s24",
    chapter: "الفصل السادس — الكابوس",
    title: "إغلاق الفندق",
    time: "7:18 ص",
    place: "الفندق بأكمله",
    bg: "hallway_red",
    mood: "red",
    lines: [
      { who: "system", text: "بروتوكول الإغلاق — تنفيذ" },
      { who: "narrator", text: "الأبواب تُقفل. المصاعد تتوقف. إشارة الهاتف تختفي.", stage: true, shake: true },
      { who: "narrator", text: "صفارات الإنذار تبدأ. الضيوف يهرعون في الممرات.", stage: true },
      { who: "narrator", text: "على كل سلّم رجل أمن.", stage: true },
    ],
    choicePrompt: "كيف تعبر الفندق؟",
    choices: [
      {
        id: "tunnels",
        text: "أنفاق الصيانة.",
        requires: (s) => s.flags.stoleNoahKey || s.trust.noah >= 30,
        effect: { trust: { noah: 5 } },
        goto: "s25",
      },
      {
        id: "crowd",
        text: "امشِ وسط الضيوف. لا يجرؤون على إمساكك أمامهم.",
        effect: { trust: { maya: 5 } },
        goto: "s25",
      },
      {
        id: "garage",
        text: "المرآب. اخرج ثم عُد من باب الخدمة.",
        effect: { trust: { claire: 5 } },
        goto: "s25",
      },
    ],
  },
  {
    id: "s25",
    chapter: "الفصل السادس — الكابوس",
    title: "قاعة الاحتفالات",
    time: "7:41 ص",
    place: "القاعة الكبرى",
    bg: "ballroom",
    mood: "red",
    lines: [
      { who: "narrator", text: "مئات الضيوف محتجزون. فيكتور يظهر على المسرح. صوته ثابت كالعادة.", stage: true },
      { who: "victor", text: "نرجو من الجميع البقاء هادئين." },
      { who: "narrator", text: "الأنوار تنطفئ.", stage: true, shake: true },
      { who: "narrator", text: "وحين تعود، فيكتور ليس هناك.", stage: true },
      { who: "narrator", text: "على المسرح جسد.", stage: true },
      { who: "daniel", text: "…نواه." },
      {
        who: "narrator",
        text: "لكن الصدر يتحرك. إنه يتنفس. أحدهم أراد لدانيال أن يراه ميتاً.",
        stage: true,
        requires: (s) => s.trust.noah >= 20,
      },
      {
        who: "narrator",
        text: "الصدر لا يتحرك. نواه كين مات في قاعة يعرف كل كاميرا فيها.",
        stage: true,
        requires: (s) => s.trust.noah < 20,
      },
    ],
    next: (s) => (s.trust.noah >= 20 ? "s26" : "s25b"),
  },
  {
    id: "s25b",
    chapter: "الفصل السادس — الكابوس",
    title: "بعد نواه",
    place: "القاعة الكبرى",
    bg: "ballroom",
    mood: "red",
    lines: [
      { who: "maya", text: "لم يكن شاهداً. كان دليلاً. والأدلة تُنظَّف." },
      { who: "daniel", text: "إذاً لم يبقَ سوانا." },
    ],
    onEnter: { kill: ["noah"] },
    next: "s26",
  },
  {
    id: "s26",
    chapter: "الفصل السادس — الكابوس",
    title: "الغرفة ٣١٠ مرة أخرى",
    time: "8:06 ص",
    place: "الغرفة ٣١٠",
    bg: "room310",
    mood: "dark",
    lines: [
      { who: "narrator", text: "يعود إلى الغرفة. كل شيء تغيّر.", stage: true },
      { who: "narrator", text: "الجدران مغطاة بالصور. دانيال. إيلاياس. كلير. مايا. نواه. فيكتور.", stage: true },
      { who: "narrator", text: "وبينها أوراق: كل قرار اتخذه دانيال الليلة، مكتوباً قبل أن يتخذه.", stage: true, shake: true },
    ],
    onEnter: { evidence: ["wall_photos"] },
    inspectPrompt: "الجدار كبير. ابحث عن ما لا ينتمي إليه.",
    minInspect: 1,
    inspect: [
      {
        id: "wallpaper_seam",
        label: "خيط في ورق الجدار",
        x: 74,
        y: 48,
        lines: [
          { who: "narrator", text: "الورق مفتوح من الحافة. خلفه لا جبس، بل هواء.", stage: true },
          { who: "narrator", text: "باب. وخلفه غرفة ثانية.", stage: true, shake: true },
          { who: "system", text: "٣١٠ ب" },
        ],
        effect: { secrets: ["room310b"], set: { discoveredRoom310B: true } },
      },
      {
        id: "wall_maya",
        label: "صورة مايا",
        x: 30,
        y: 40,
        lines: [
          { who: "narrator", text: "صورة مايا مأخوذة داخل قسم الشرطة. من زاوية عالية.", stage: true },
          { who: "daniel", text: "هم داخل القسم أيضاً." },
        ],
        effect: { trust: { maya: 5 } },
      },
      {
        id: "wall_own",
        label: "صورة دانيال",
        x: 52,
        y: 34,
        lines: [
          { who: "narrator", text: "دانيال في هذه الغرفة. مبتسم. يجلس على نفس السرير.", stage: true },
          { who: "system", text: "قبل خمس سنوات" },
        ],
        effect: { secrets: ["memory_wiped"] },
      },
    ],
    next: (s) => (s.flags.discoveredRoom310B ? "s27" : "s28"),
  },
  {
    id: "s27",
    chapter: "الفصل السادس — الكابوس",
    title: "٣١٠ب",
    time: "8:22 ص",
    place: "الغرفة ٣١٠ب",
    bg: "room310b",
    mood: "dark",
    lines: [
      { who: "narrator", text: "غرفة بلا نافذة. كرسي واحد. كاميرا واحدة. شاشة واحدة.", stage: true },
      { who: "narrator", text: "الشاشة تعرض دانيال. مباشرة.", stage: true },
      { who: "narrator", text: "ثم يتغير الطابع الزمني.", stage: true, shake: true },
      { who: "system", text: "قبل خمس سنوات" },
      { who: "narrator", text: "يرى نفسه يدخل هذه الغرفة. مع إيلاياس.", stage: true },
      { who: "daniel", text: "أنا لا أتذكر هذا…" },
      { who: "narrator", text: "ثم يسمع صوته هو:", stage: true },
      { who: "daniel", text: "«إن لم نستطع فضحهم، نجعلهم يعتقدون أننا ميتان.»" },
      { who: "narrator", text: "الكرسي أمامه فيه أحزمة. والأحزمة مستعملة.", stage: true },
    ],
    onEnter: {
      secrets: ["room310b", "memory_wiped", "daniel_helped_elias"],
      set: { discoveredRoom310B: true },
    },
    next: "s28",
  },
];
