import type { Scene } from "../types";

export const act7: Scene[] = [
  {
    id: "s28",
    chapter: "الفصل السابع — الذاكرة المفقودة",
    title: "الحقيقة",
    time: "8:40 ص",
    place: "الغرفة ٣١٠",
    bg: "room310",
    mood: "dark",
    lines: [
      {
        who: "narrator",
        text: "القطع تنطبق واحدة تلو الأخرى، بترتيب لا يريده أحد.",
        stage: true,
      },
      { who: "narrator", text: "إيلاياس لم يُختطف.", stage: true },
      { who: "narrator", text: "دانيال هو من ساعده على الاختفاء.", stage: true, shake: true },
      { who: "narrator", text: "كانا يخططان لفضح الدائرة. ثم انحرف كل شيء.", stage: true },
      { who: "narrator", text: "دانيال خُدِّر. إيلاياس أُخذ. وذاكرة دانيال أُعيدت كتابتها.", stage: true },
      { who: "daniel", text: "خمس سنوات… وأنا أبحث عن قاتل أخي." },
      { who: "daniel", text: "وأنا الذي أوصلته إليهم." },
    ],
    onEnter: {
      secrets: ["daniel_helped_elias", "memory_wiped"],
      set: { playerMemoryRecovered: true },
    },
    choicePrompt: "الذاكرة عادت. ماذا تفعل بها؟",
    choices: [
      {
        id: "own_it",
        text: "اعترف بها. اكتبها في ملفك بيدك.",
        effect: { trust: { maya: 15 }, secrets: ["memory_wiped"] },
        goto: "s29",
      },
      {
        id: "hide_it",
        text: "اخفِها عن الجميع. حتى عن مايا.",
        effect: { trust: { maya: -10, claire: 10 } },
        goto: "s29",
      },
    ],
  },
  {
    id: "s29",
    chapter: "الفصل السابع — الذاكرة المفقودة",
    title: "التسجيل الأخير",
    time: "8:55 ص",
    place: "الغرفة ٣١٠ب",
    bg: "room310b",
    mood: "dark",
    lines: [
      { who: "narrator", text: "قرص صغير في ظهر الكرسي. ملف واحد. وجه إيلاياس.", stage: true },
      { who: "elias", text: "دانيال." },
      { who: "elias", text: "إذا كنت تشاهد هذا، فمعناه أنهم فشلوا." },
      { who: "elias", text: "لم يكن مفترضاً أن تتذكر." },
      { who: "elias", text: "كلير ستجدك." },
      { who: "elias", text: "ستقول لك إنني مِت." },
      { who: "elias", text: "لا تصدّقها." },
      { who: "narrator", text: "ينتهي الفيديو.", stage: true, shake: true },
      { who: "narrator", text: "دانيال يرفع عينيه إلى كلير.", stage: true },
    ],
    onEnter: {
      evidence: ["elias_recorder"],
      secrets: ["elias_alive"],
      set: { foundEliasFinalVideo: true },
    },
    next: "s30",
  },
  {
    id: "s30",
    chapter: "الفصل السابع — الذاكرة المفقودة",
    title: "سر كلير",
    time: "9:07 ص",
    place: "الغرفة ٣١٠",
    bg: "room310",
    mood: "cold",
    lines: [
      { who: "daniel", text: "أنتِ تعرفين أنه حيّ." },
      { who: "claire", text: "…نعم." },
      { who: "daniel", text: "منذ متى؟" },
      { who: "claire", text: "خمس سنوات." },
      { who: "daniel", text: "خمس سنوات وأنا أزور قبراً فارغاً." },
      { who: "claire", text: "لم أكن أعرف إن كنتَ منهم." },
      { who: "claire", text: "ملفك في الأرشيف يقول «مُراقَب». وملف فيكتور يقول نفس الكلمة." },
      { who: "claire", text: "استخدمتُك لأجده. هذه هي الحقيقة." },
    ],
    choicePrompt: "كلير تنتظر ردك.",
    choices: [
      {
        id: "forgive",
        text: "«كنتِ خائفة. أفهم.»",
        effect: { trust: { claire: 20 } },
        goto: "s31",
      },
      {
        id: "cut",
        text: "«إذاً نحن اثنان استُخدما. لا شركاء.»",
        effect: { trust: { claire: -15, maya: 10 } },
        goto: "s31",
      },
      {
        id: "test",
        text: "«أعطيني اسم من يحرسه. الآن.»",
        effect: { trust: { claire: 5 }, secrets: ["circle_leader"] },
        goto: "s31",
      },
    ],
  },
];
