import type { Scene } from "../types";

export const endings: Scene[] = [
  {
    id: "e01",
    kind: "ending",
    endingCode: "e01",
    endingTitle: "الحقيقة",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية الأولى",
    place: "مكتب دانيال",
    bg: "apartment",
    mood: "cold",
    lines: [
      { who: "narrator", text: "مايا تُسلّم النسخ إلى ثلاث جهات لا تعرف إحداها الأخرى.", stage: true },
      { who: "narrator", text: "وسبع صحف تنشر في نفس الساعة. لا أحد يستطيع إسكات سبعة.", stage: true },
      { who: "narrator", text: "الدائرة تتفتت. فيكتور هيل يُعتقل. مسؤولون يختفون.", stage: true },
      { who: "narrator", text: "كلير تنجو. إيلاياس يدخل برنامج حماية الشهود.", stage: true },
      { who: "narrator", text: "دانيال ينشر القصة كاملة، باسمه.", stage: true },
      { who: "narrator", text: "المشهد الأخير: دانيال على مكتبه. رسالة تظهر على الشاشة.", stage: true },
      { who: "unknown", text: "ظننتَ أن الأمر انتهى." },
      { who: "narrator", text: "ينظر إلى الشاشة. قطع إلى الأسود.", stage: true },
    ],
  },
  {
    id: "e02",
    kind: "ending",
    endingCode: "e02",
    endingTitle: "الناجي",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية الثانية",
    place: "مدينة أخرى",
    bg: "drive",
    mood: "rain",
    lines: [
      { who: "narrator", text: "يخرجان من الفندق قبل الفجر. لا أحد يوقفهما.", stage: true },
      { who: "narrator", text: "الدليل لا يُنشر أبداً. الدائرة تبقى حيّة، وتنسى أسماءهما مؤقتاً.", stage: true },
      { who: "narrator", text: "دانيال يغيّر هويته. كلير تختفي كما تعرف أن تختفي.", stage: true },
      { who: "narrator", text: "بعد سنوات، يصل إليه صندوق صغير بلا مُرسِل.", stage: true },
      { who: "narrator", text: "داخله مفتاح واحد. ورقمه: ٣١٠.", stage: true, shake: true },
      { who: "narrator", text: "ينظر إليه طويلاً. قطع إلى الأسود.", stage: true },
    ],
  },
  {
    id: "e03",
    kind: "ending",
    endingCode: "e03",
    endingTitle: "الشهيد",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية الثالثة",
    place: "لوبي هالسيون",
    bg: "lobby",
    mood: "red",
    lines: [
      { who: "narrator", text: "يرفع الملف كله إلى الشبكة، ثم يرفض أن يخرج من الفندق.", stage: true },
      { who: "daniel", text: "لن أترك المكان قبل أن أراه ينهار." },
      { who: "narrator", text: "فيكتور ينزل السلم. هادئ كما كان طوال الليل.", stage: true },
      { who: "victor", text: "كان بإمكانك أن تعيش." },
      { who: "narrator", text: "طلقة واحدة.", stage: true, shake: true },
      { who: "narrator", text: "الرفع يكتمل بعد أربع دقائق من موته.", stage: true },
      { who: "narrator", text: "كلير تشاهد الأخبار من غرفة فندق أخرى. مايا تبكي في سيارتها.", stage: true },
      { who: "narrator", text: "دانيال فيل يصبح الصحافي الذي فضح الدائرة.", stage: true },
      { who: "narrator", text: "المشهد الأخير: الغرفة ٣١٠. فارغة.", stage: true },
    ],
  },
  {
    id: "e04",
    kind: "ending",
    endingCode: "e04",
    endingTitle: "الصفقة",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية الرابعة",
    place: "فندق آخر",
    bg: "lobby",
    mood: "warm",
    lines: [
      { who: "narrator", text: "يقبل العرض. كلير تختفي. إيلاياس يُفرَج عنه بشرط الصمت.", stage: true },
      { who: "narrator", text: "خمسة ملايين. وعقد عمل في صحيفة لم تكن تردّ على رسائله.", stage: true },
      { who: "narrator", text: "مسيرته تصعد. جوائز. برامج. اسم على غلاف.", stage: true },
      { who: "narrator", text: "بعد سنوات يدخل فندقاً في مدينة أخرى.", stage: true },
      { who: "receptionist", text: "غرفتك جاهزة، سيد فيل. ٣١٠." },
      { who: "narrator", text: "ينظر إلى الكاميرا في السقف.", stage: true, shake: true },
      { who: "narrator", text: "ويفهم أنه صار جزءاً من الدائرة.", stage: true },
    ],
  },
  {
    id: "e05",
    kind: "ending",
    endingCode: "e05",
    endingTitle: "الدائرة",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية الخامسة",
    place: "مكتب المدير",
    bg: "security",
    mood: "cold",
    lines: [
      { who: "narrator", text: "لا يفضح الشبكة. يستولي عليها.", stage: true },
      { who: "narrator", text: "كل اسم في القرص يصبح ورقة ضغط بيده.", stage: true },
      { who: "narrator", text: "فيكتور هيل يموت في «حادث» بعد أحد عشر يوماً.", stage: true },
      { who: "narrator", text: "دانيال يجلس في مكانه.", stage: true },
      { who: "narrator", text: "كلير تفهم ما حدث. تختفي بلا وداع.", stage: true },
      { who: "narrator", text: "مايا تفتح ملفاً جديداً. الاسم عليه: دانيال فيل.", stage: true },
      { who: "system", text: "الهدف التالي" },
      { who: "narrator", text: "دانيال يبتسم.", stage: true, shake: true },
    ],
  },
  {
    id: "e06",
    kind: "ending",
    endingCode: "e06",
    endingTitle: "الأخ",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية السادسة",
    place: "ساحل بعيد",
    bg: "rooftop",
    mood: "warm",
    lines: [
      { who: "narrator", text: "يختار أخاه على كل شيء آخر. القرص يُحرق أمامهما.", stage: true },
      { who: "narrator", text: "يهربان قبل أن تُفتح الأبواب. الدائرة تبقى، وتنساهما.", stage: true },
      { who: "narrator", text: "بعد سنوات، على شرفة صغيرة قرب البحر:", stage: true },
      { who: "daniel", text: "هل كان يستحق؟" },
      { who: "elias", text: "اسألني حين نموت." },
      { who: "narrator", text: "قطع إلى الأسود.", stage: true },
    ],
  },
  {
    id: "e07",
    kind: "ending",
    endingCode: "e07",
    endingTitle: "الخيانة",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية السابعة",
    place: "مكتب مجهول",
    bg: "security",
    mood: "cold",
    lines: [
      { who: "narrator", text: "يعطي القرص لكلير. تأخذه بيدين ثابتتين أكثر من اللازم.", stage: true },
      { who: "claire", text: "شكراً يا دانيال." },
      { who: "narrator", text: "ثم يفهم متأخراً: كلير هي من رتّبت الليلة كلها.", stage: true, shake: true },
      { who: "narrator", text: "أُحضِر إلى الغرفة ٣١٠ لأنه الوحيد القادر على فتح دليل إيلاياس الأخير.", stage: true },
      { who: "narrator", text: "الشرطة تصل. تُهمة حيازة مواد مسروقة وتلاعب بمسرح جريمة.", stage: true },
      { who: "narrator", text: "المشهد الأخير: كلير تدخل مكتباً لا نعرفه.", stage: true },
      { who: "victor", text: "هل تذكّر؟" },
      { who: "claire", text: "بما يكفي." },
      { who: "narrator", text: "قطع إلى الأسود.", stage: true },
    ],
  },
  {
    id: "e08",
    kind: "ending",
    endingCode: "e08",
    endingTitle: "الفندق الفارغ",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية الثامنة",
    place: "هالسيون",
    bg: "ballroom",
    mood: "red",
    lines: [
      { who: "narrator", text: "الخوادم. السجلات. الملفات. الأدلة. كل شيء.", stage: true },
      { who: "narrator", text: "الحريق يبدأ من الأرشيف السفلي ولا يتوقف.", stage: true, shake: true },
      { who: "narrator", text: "الجميع يخرج. إلا فيكتور، الذي بقي مع أرشيفه.", stage: true },
      { who: "narrator", text: "بعد أشهر، يُهدَم فندق هالسيون. الأرض تُبنى كموقف سيارات.", stage: true },
      { who: "narrator", text: "دانيال يعتقد أن الأمر انتهى.", stage: true },
      { who: "narrator", text: "ثم تصل صورة إلى هاتفه. الغرفة ٣١٠. سليمة تماماً.", stage: true },
      { who: "system", text: "الطابع الزمني: غداً" },
    ],
  },
  {
    id: "e09",
    kind: "ending",
    endingCode: "e09",
    endingTitle: "الحلقة",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية التاسعة",
    place: "الغرفة ٣١٠ب",
    bg: "room310b",
    mood: "dark",
    lines: [
      { who: "narrator", text: "على الشاشة في ٣١٠ب مجلد واحد لم يفتحه أحد.", stage: true },
      { who: "system", text: "دانيال فيل — الجلسة ٣١" },
      { who: "narrator", text: "الغرفة ٣١٠ ليست غرفة. إنها أداة.", stage: true },
      { who: "narrator", text: "دانيال عاش هذه الليلة قبل الآن. عشرات المرات.", stage: true, shake: true },
      { who: "narrator", text: "كل نسخة انتهت بشكل مختلف. وكل مرة نسي.", stage: true },
      { who: "narrator", text: "…", stage: true },
      { who: "system", text: "1:47 ص" },
      { who: "narrator", text: "الهاتف يرن. رقم مجهول. يرد.", stage: true },
      { who: "unknown", text: "دانيال؟" },
      { who: "daniel", text: "…كلير." },
      { who: "narrator", text: "الشاشة تخبو. اللعبة تبدأ من جديد.", stage: true },
      { who: "narrator", text: "لكن تفاصيل صغيرة ستكون مختلفة.", stage: true },
    ],
  },
  {
    id: "e10",
    kind: "ending",
    endingCode: "e10",
    endingTitle: "الغرفة",
    chapter: "الفصل التاسع — النهايات",
    title: "النهاية العاشرة",
    place: "سطح هالسيون / ممر لا ينتهي",
    bg: "rooftop",
    mood: "rain",
    lines: [
      { who: "narrator", text: "قائد الدائرة ليس فيكتور. ولا نواه. ولا كلير.", stage: true },
      { who: "narrator", text: "إيلاياس فيل هو من أنشأ مشروع أورفيوس.", stage: true, shake: true },
      { who: "narrator", text: "الحادث كان مُرتّباً. كلير جُنِّدت. ودانيال… استُخدم.", stage: true },
      { who: "elias", text: "الناس لا يخافون الحقيقة. يخافون أن يعرفها أحد." },
      {
        who: "narrator",
        text: "دانيال أطلق النار. الشبكة كلها نُشرت تلقائياً في اللحظة التي توقف فيها قلب إيلاياس.",
        stage: true,
        requires: (s) => !s.alive.elias,
      },
      {
        who: "narrator",
        text: "دانيال خرج ولم ينظر خلفه. إيلاياس اختفى. الدائرة استمرّت.",
        stage: true,
        requires: (s) => s.alive.elias,
      },
      { who: "unknown", text: "الغرفة ٣١٠ تنتظر دائماً." },
      { who: "narrator", text: "الكاميرا تتقدم نحو الباب. الرقم يتغيّر.", stage: true },
      { who: "system", text: "٣١٠" },
      { who: "system", text: "٣٠٩" },
      { who: "system", text: "٣٠٨" },
      { who: "system", text: "٣٠٧" },
      { who: "narrator", text: "الممر يستمر إلى ما لا نهاية. قطع إلى الأسود.", stage: true },
      { who: "system", text: "لكل غرفة سِرّ." },
    ],
  },
];
